package com.pojo;
// Generated Aug 29, 2018 9:12:48 AM by Hibernate Tools 5.2.3.Final

/**
 * Admin generated by hbm2java
 */
public class Admin implements java.io.Serializable {

	private Integer aid;
	private String username;
	private String password;

	public Admin() {
	}

	public Admin(String username, String password) {
		this.username = username;
		this.password = password;
	}

	public Integer getAid() {
		return this.aid;
	}

	public void setAid(Integer aid) {
		this.aid = aid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
