package com.pojo;
// Generated Aug 29, 2018 9:12:48 AM by Hibernate Tools 5.2.3.Final

/**
 * Availability generated by hbm2java
 */
public class Availability implements java.io.Serializable {

	private Integer avid;
	private String location;
	private Integer pincode;

	public Availability() {
	}

	public Availability(String location, Integer pincode) {
		this.location = location;
		this.pincode = pincode;
	}

	public Integer getAvid() {
		return this.avid;
	}

	public void setAvid(Integer avid) {
		this.avid = avid;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public Integer getPincode() {
		return this.pincode;
	}

	public void setPincode(Integer pincode) {
		this.pincode = pincode;
	}

}
