package com.pojo;
// Generated Aug 29, 2018 9:12:48 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

	private Integer oid;
	private Product product;
	private Register register;
	private String orderId;
	private Date orderDate;

	public Order() {
	}

	public Order(Product product, Register register, String orderId, Date orderDate) {
		this.product = product;
		this.register = register;
		this.orderId = orderId;
		this.orderDate = orderDate;
	}

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Register getRegister() {
		return this.register;
	}

	public void setRegister(Register register) {
		this.register = register;
	}

	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

}
