package com.pojo;
// Generated Aug 29, 2018 9:12:48 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private Integer pid;
	private String productId;
	private String proname;
	private String manufacturedDate;
	private String expireDate;
	private Double price;
	private Set orders = new HashSet(0);

	public Product() {
	}

	public Product(String productId, String proname, String manufacturedDate, String expireDate, Double price,
			Set orders) {
		this.productId = productId;
		this.proname = proname;
		this.manufacturedDate = manufacturedDate;
		this.expireDate = expireDate;
		this.price = price;
		this.orders = orders;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getProname() {
		return this.proname;
	}

	public void setProname(String proname) {
		this.proname = proname;
	}

	public String getManufacturedDate() {
		return this.manufacturedDate;
	}

	public void setManufacturedDate(String manufacturedDate) {
		this.manufacturedDate = manufacturedDate;
	}

	public String getExpireDate() {
		return this.expireDate;
	}

	public void setExpireDate(String expireDate) {
		this.expireDate = expireDate;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Set getOrders() {
		return this.orders;
	}

	public void setOrders(Set orders) {
		this.orders = orders;
	}

}
